# https://taskfile.dev/

version: '3'

interval: 1s

vars:
  JS_BUNDLE: public/bundle.js
  CSS_BUNDLE: public/bundle.css

  EXE: bin/app{{exeExt}}

  CMD_RM: bin/rm{{exeExt}}
  CMD_CP: bin/cp{{exeExt}}
  CMD_OPEN: bin/open{{exeExt}}

tasks:
  default:
    desc: Build and run the web app
    aliases: [run]
    cmds:
      - task: build
      - ./{{.EXE}}
  
  install:
    desc: Install dependencies
    cmds:
      - go build -v -o {{.CMD_RM}} ./cmd/rm
      - go build -v -o {{.CMD_CP}} ./cmd/cp
      - go build -v -o {{.CMD_OPEN}} ./cmd/open

  build:
    desc: Build the web app
    deps: [js, css]
    cmds:
      - go build -v -o {{.EXE}} ./app.go
    sources:
      - '**/*.go'
      - '{{.JS_BUNDLE}}'
      - '{{.CSS_BUNDLE}}'
      - templates/**/*
    generates:
      - '{{.EXE}}'

  js:
    desc: Bundle JS using esbuild
    cmds:
      - esbuild --bundle --minify assets/js/index.js > {{.JS_BUNDLE}}
    sources:
      - assets/js/**/*.js
    generates:
      - '{{.JS_BUNDLE}}'

  css:
    desc: Bundle CSS using esbuild
    cmds:
      - esbuild --bundle --minify assets/css/index.css > {{.CSS_BUNDLE}}
    sources:
      - assets/css/**/*.css
    generates:
      - '{{.CSS_BUNDLE}}'

  clean:
    desc: Clean every generated file
    cmds:
      - ./{{.CMD_RM}} {{.CSS_BUNDLE}}
      - ./{{.CMD_RM}} {{.JS_BUNDLE}}
      - ./{{.CMD_RM}} {{.EXE}}
