name: Release Build

on:
 push:
  paths:
    - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up esbuild
        run: |
          npm --version
          npm install -g esbuild
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install tools
        run: task install
      - name: Clean
        run: task clean
      - name: Build
        run: task build
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
      - name: Zip
        run: |
          cd bin
          zip -r app_v${{ steps.version.outputs.content }}.zip ./app
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/app_v${{ steps.version.outputs.content }}.zip
          token: '${{ secrets.GITHUB_TOKEN }}'
          draft: false
          prerelease: false
          name: app_v${{ steps.version.outputs.content }}
          body: app_v${{ steps.version.outputs.content }} release
          tag_name: v${{ steps.version.outputs.content }}
      - name: Done
        run: echo "All jobs have been done. 🚀"
