name: Release Build

on push:
  branches:
    - main
  paths:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up esbuild
        run: |
          npm --version
          npm install -g esbuild
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
        run: go version
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install tools
        run: task install
      - name: Clean
        run: task clean
      - name: Build
        run: task build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
